swagger: '2.0'
info:
  title: Example API
  description: Example API
  version: 0.0.1
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
basePath: /v1
tags:
  - name: blacklist
    description: |
      Lets you **view** blacklist. Can be run by any authenticated user in the system as long as they have the privileges to do so.
securityDefinitions:
  isRegistered:
    type: basic
  isAuthenticated:
    type: apiKey
    in: header
    name: Authorization
security:
  - isAuthenticated: []
paths:
  /blacklist:
    get:
      tags:
        - blacklist
      summary: Get blacklist endpoint
      security: []
      operationId: GetBlackList
      description: This responds with a 200 on success
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Blacklist'
        '400':
        '404':
        '500':

definitions:
  principal:
    type: object
    properties:
      userId:
        type: string
      companyId:
        type: string
      userName:
        type: string
      roles:
        type: array
        items:
          type: string
  Blacklist:
    title: Blacklist
    type: object
    properties:
      domains:
        type: array
        items:
          type: string
